### PR TITLE
Create .gitattributes

### PR DESCRIPTION
**Pull request by reedy**

### CODE REVIEW

**Comment by shadowhand** [comment]
How come?

**Comment by Nyholm** [comment]
Closing due inactivity. Feel free to reopen if this is still important.

**Comment by reedy** [comment]
I'm not sure what activity is needed. It's pretty self explanatory

**Comment by shadowhand** [comment]
But what benefit would this have? None of these files are problematic.

**Comment by reedy** [comment]
They're not, but they're also unnecessary for someone "checking out" the library via composer. The library does not need them to function. If I was developing/making changes to this library, I would be using a proper git clone. So what benefit do they have staying around?

If you then times this problem across tens or hundreds of libraries (that similarly don't have dot files and tests etc in .gitattributes), it increases the file count and disk space used by some amount. Then depending on your deploymemt methods, you've potentially got to copy (via whatever means) these to many servers...

**Comment by reedy** [comment]
https://php.watch/articles/composer-gitattributes

>Using a .gitattributes file function called export-ignore, it is possible to dramatically reduce the file size of a Composer package download. 

Obviously in this case, it doesn't dramatically reduce it, but it all adds up

**Pull request closed without merging**
