### PR TITLE
Added missing exceptions for StreamFactoryInterface:createStreamFromFile

### PR DESCRIPTION
**Pull request by MarcHagen**

### CODE REVIEW

**Review by Jean85 — APPROVED** [review]
This seems in fact a difference from the PSR text, that should be taken as base.

BTW the editor (@shadowhand) has the final say on this.

**Comment by Jean85** [comment]
For reference: https://www.php-fig.org/psr/psr-17/#24-streamfactoryinterface

**Review by shadowhand — APPROVED** [review]

**Comment by shadowhand** [comment]
@Jean85 do I merge and tag this, or does a secretary do that?

cc @weierophinney

**Comment by Jean85** [comment]
No strict requirement on that, feel free to do that yourself!

**Comment by shadowhand** [comment]
Tagged in 1.0.1.

**Comment by michaelcullum** [comment]
Except they should be signed... https://github.com/php-fig/fig-standards/blob/master/CONTRIBUTING.md#tagging

**Comment by shadowhand** [comment]
@michaelcullum I always sign my commits/tags:

Image 2019-05-22 at 9 31 46 AM

**Pull request merged**
